### ISSUE TITLE
Implement Landing Page 

### ISSUE THREAD

**Issue by Khauthymo** [Custos-Diretriz/custos-mobile#1]
- [ ] Work on UI for the landing page and implement screens as seen on the figma
- [ ] Implement animations as seen on the figma:
https://www.figma.com/design/3nZ7dFPCVz4fdnfP5ZGlL6/Custos-Diretriz?node-id=0-1&node-type=canvas&t=MFsQFI1P8Haph2Wl-0

**Comment by Jemiiah** [comment]
I would love to work on this issue @Khauthymo my first time on this project 🚀

**Comment by martinvibes** [comment]
Hello @Goodness5 @Khauthymo I'm a frontend d3v and a blockchain  dev I would like to work on this issue :) this will be my first time contributing on this project if I'm assigned

**Comment by abdegenius** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a fullstack developer worked with various frontend frameworks over the years as well as different backend languages. currently transitioning into the web3 space.

### How I plan on tackling this issue
Using Sveltekit and Tailwindcss I will create a well documented and written codebase that will capture every bit of detail of the figma design and bring it to live, with the animations, mobile responsiveness, dark and light mode features as well as componentization for reusability across other pages, ican very much handle this task!

**Comment by Oshioke-Salaki** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Gm i am a well versed frontend developer with large experience in building large scale web applications and dapp and i believe i would be able to tackle this effectively.

### How I plan on tackling this issue
I would develop the page perfectly according to the figma design and also make sure that it is responsive in all screens. I will make sure to adopt best practices when builidng to ensure a pixel perfect build

**Comment by Mystic-Nayy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a frontend developer and i have a lot of experience in open source contribution

### How I plan on tackling this issue
I will Design and implement the landing page UI based on the Figma specifications, ensuring that all elements are accurately represented. Integrate animations and transitions as outlined in the Figma design to enhance the user experience. Test the responsiveness and functionality of the landing page to ensure it meets the design requirements.

**Comment by Ayoazeez26** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a software developer with over 6 years experience in building applications

### How I plan on tackling this issue
Use the figma design as a guide to implement screens to pixel perfect integration and also implement animations and ensure all these work perfectly on all browsers and all devices

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, and Rust. With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
To create an engaging landing page for the web version of the app, I will focus on developing the user interface (UI) based on the designs provided in Figma. The implementation will prioritize responsive design to ensure a seamless experience across different screen sizes.

I will translate the Figma screens into React components, ensuring that all elements, including text, images, and buttons, are accurately represented. Additionally, I will incorporate animations as specified in the Figma design to enhance user interaction and visual appeal. These animations will be smooth and intuitive, adding an extra layer of engagement for users as they navigate through the landing page.

Throughout the development process, I will ensure adherence to best practices for performance optimization and maintainability, while also testing the page for responsiveness and usability. This approach will result in a visually appealing and user-friendly landing page that effectively captures the essence of the app and encourages user engagement.

**Comment by KevinLatino** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I have a deep passion for Web3 and I am currently working as a frontend developer intern at a Web2 company, focusing on Next.js. Additionally, I am an active member of Dojo Coding, a prominent Web3 community in LATAM, which has given me great exposure to decentralized technologies.

Recently, I have been working on a project for Base LATAM's Buildathon, where I am gaining hands-on experience in building decentralized applications. I am eager to continue growing and contributing, and see this as a fantastic opportunity to further develop my skills and make a significant impact.

This is my first OD Hack, so I will appreciate it if you give me the chance to contribute to this amazing project.

Some frontend projects that i have:                                                               
https://buildmyevent.xyz/
https://peritazgo-website.vercel.app/



### How I plan on tackling this issue
To resolve this issue effectively, I would start by thoroughly reviewing the Figma design to fully understand the structure and layout of the landing page. I’d pay close attention to the sections, typography, spacing, and color scheme to ensure every detail is accounted for.

Once I grasp the design, I would move on to implementing the UI, focusing on accurately recreating the layout and elements as specified in Figma. Throughout the development, I would use best practices like Flexbox or Grid for layout management to ensure the code is clean and maintainable.

After the basic structure is in place, I’d refine all details, ensuring the page is fully responsive across various screen sizes and devices. I would continuously test the layout during development to ensure everything aligns with the Figma design and functions smoothly.

Finally, I’d perform a thorough round of testing to make sure the landing page matches the Figma design precisely, both visually and functionally. @Khauthymo I hope you give me the opportunity to contribute to this amazing project; I would be very grateful.

**Comment by melnikga** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hi, my name is Georgiy, I'm a frontend developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

### How I plan on tackling this issue
I would create all the main landing page sections according to the Figma design, implementing responsive layouts for each screen. For components, I'd use shadcn's built-in elements to maintain a clean and professional look, particularly for buttons, cards, and navigation. I'd implement smooth animations using Framer Motion, ensuring they match the Figma specifications - this includes scroll-triggered animations, hover effects, and page transitions. For optimization, I'd set up lazy loading for images and components to ensure fast initial page load. I'd also make sure to test the animations across different devices to maintain consistent performance.

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I'm a web2 and web3 developer, want to contribute to the open source projects and fix issues.

### How I plan on tackling this issue
I would implement the landing page UI as designed in Figma, making sure the screens are pixel-perfect and responsive on every possible type of device. Also, i would implement the specified Figma animations with efforts towards having smooth interaction within the view.

**Comment by sasasamaes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Full Stack developer with 5+ years of experience involved in the full software development lifecycle. My experience includes providing IT solutions for enterprises using JavaScript, React, TypeScript, Node.js, and MongoDB. Additionally, I am expanding my knowledge in Web3 technologies, particularly in Cairo and Solidity.

I am also a community leader and sensei at Dev.f, where I mentor and lead a vibrant community of developers and am a Dojo Coding Member.

My areas of interest include Web3, frontend, backend, and full-stack development.

### How I plan on tackling this issue
I could go from figma to a landing page in react, add animations as indicated and it could last between 2 to 3 days

**Comment by Goodness5** [comment]
@martinvibes you can access figma design here in-case you ommited it in the contribution guidelines https://www.figma.com/design/3nZ7dFPCVz4fdnfP5ZGlL6/Custos-Diretriz?node-id=0-1&node-type=canvas&t=SZrQbCkWDo6zOuvO-0

**Comment by faytey** [comment]
@martinvibes are you still actively working on this

**Comment by martinvibes** [comment]
Hey @faytey yes I'm making PR soon
