### ISSUE TITLE
General Components

### ISSUE THREAD

**Issue by Khauthymo** [Custos-Diretriz/custos-mobile#2]
- [ ] Implement nav bar and connect wallet component

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a frontend developer with experience in using JavaScript, React, typescript and basic understanding of smart contract.



### How I plan on tackling this issue
- First, I'll set up the basic structure of the Navbar component
- Next, I'll implement the navigation links
- Then, I'll create a function to render these links
- Now, i'll add the connect wallet button using Wagmi's ConnectButton
- Finally, I'll combine everything in the component

with the above steps i believe i would be able to implement the above. Kindly assign me. ETA <= 48hrs

**Comment by ryzen-xp** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged

I am a Full stack Blockchain developer with expertise in Cairo, Solidity, Rust, and Web2 . I’ve contributed to open-source projects such as Worldcoin-Bridge-Linea and ArkProjectNFTs Bridge

### How I plan on tackling this issue
I’d design the navigation bar and wallet connection component, integrate the wallet functionality, and then test everything to ensure it works smoothly.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
hello @Khauthymo i'm an experienced frontend developer and a blockchain developer i would love to work on this issue 
Pleasee kindly assign :)

### How I plan on tackling this issue
i would simply  read and follow the instructions and make sure it is implemented to pixel perfect 
kindly assign :)

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/

### How I plan on tackling this issue
I will ensure that all the criteria on the desciption ar met by Implement nav bar and connect wallet component in 2-3 days

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, and Rust. With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
I will implement a navigation bar and a wallet connection component using TypeScript. The navigation bar will provide users with easy access to key sections of the application, ensuring intuitive navigation throughout.

For the wallet connection, I will utilize Wagmi to implement WalletConnect, allowing users to connect their wallets seamlessly. This integration will facilitate interaction with blockchain features in a user-friendly manner.

The implementation will include designing the layout and styles to align with the existing design language of the app. I will ensure type safety and maintainability throughout the codebase by using TypeScript. I will create reusable components that can be easily integrated and updated in the future, promoting a consistent and efficient development process. Lastly, this will improve usability and streamline the user onboarding experience.

**Comment by chibokaxavier** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hi, I’m Chiboka Xavier, a full-stack developer with over 4 years of experience building applications that not only work well but feels great to use. I’m passionate about turning creative UI/UX designs into real, responsive user interfaces with tools like Next.js, React, and Tailwind CSS. On the backend, I use Express and MongoDB to make sure everything runs smoothly behind the scenes. I love exploring new technologies and finding ways to create seamless, enjoyable experiences for users, blending both the frontend and backend to bring ideas to life.

### How I plan on tackling this issue
To tackle this issue which involves the nav bar and connect wallet component, I'll start by checking if there are any specific requirements, like which links  options are needed. Then, I'll design a responsive nav bar using Tailwind CSS . Once I’ve built both, I’ll test them to make sure everything works smoothly and get some feedback for any tweaks needed.

**Comment by Yunusabdul38** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I have a strong background in software development, with a focus on blockchain technologies and smart contract development. My experience spans across various domains including decentralized applications (dApps), smart contract testing, and blockchain infrastructure.

With proficiency in Cairo (language), I am adept at writing and testing contracts on different blockchain platforms. I have hands-on experience with the StarkNet ecosystem and the Cairo programming language, which allows me to efficiently develop and test complex smart contracts.

Additionally, my experience with automated testing frameworks, version control systems, and continuous integration (CI) pipelines equips me to approach contract testing in a robust and scalable manner. My background in full-stack development, specifically with React and TypeScript, further strengthens my ability to contribute effectively to the frontend of decentralized applications, ensuring seamless integration with smart contracts.

Leveraging this experience, I can thoroughly implement and optimize the Cairo tests for the crime recorder and agreement contracts, ensuring high reliability and security.

### How I plan on tackling this issue
For implementing the navigation bar, I would design a clean, responsive layout using React, ensuring that key sections of the application are easily accessible. The nav bar would include links to core features such as the crime recorder, user dashboard, and any other important sections, optimized for both desktop and mobile use.

For the wallet connection component, I would integrate a wallet provider (such as MetaMask or a StarkNet-compatible wallet) using web3 libraries or StarkNet.js. This would involve creating a seamless "Connect Wallet" button that allows users to authenticate, view their account details, and interact with the crime recorder contract. I would ensure the wallet connection handles different scenarios, such as account switching or disconnections, while providing clear feedback to the user.

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I'm a blockchain developer currently looking for some issues to solve.

### How I plan on tackling this issue
I'll use React to create a responsive navigation bar and allow easy access to the main parts of the application. For the wallet component, I will add a "Connect Wallet" button using Wagmi's ConnectButton for easy wallet connection. This would ensure smooth interaction with the blockchain and will have accounted for what would happen in cases like account switching or disconnection.

**Comment by Jemiiah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hello @Goodness5 @Khauthymo I'm a frontend web 3 developer I would like to work on this issue :) this will be my first time contributing on this project if I'm assigned

### How I plan on tackling this issue
I will implement a navigation bar and a wallet connection component using TypeScript. The navigation bar will provide users with easy access to key sections of the application, ensuring intuitive navigation throughout.

For the wallet connection, I will utilize Wagmi to implement WalletConnect, allowing users to connect their wallets seamlessly. This integration will facilitate interaction with blockchain features in a user-friendly manner.

The implementation will include designing the layout and styles to align with the existing design language of the app. I will ensure type safety and maintainability throughout the codebase by using TypeScript. I will create reusable components that can be easily integrated and updated in the future, promoting a consistent and efficient development process. Lastly, this will improve usability and streamline the user onboarding experience
with ETA of 72 hours

**Comment by Ekene001** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hi, I'm Ekene, a frontend and blockchain developer, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table. Looking forward to making a positive impact and working with the team!

### How I plan on tackling this issue
To implement the navigation bar and wallet connection component, I will first design a responsive and user-friendly navigation bar that links to all key sections of the application. It will include a logo for brand identity and maintain a cohesive style with the rest of the app.

Next, I will integrate the wallet connection functionality, allowing users to securely connect their wallets. This will involve detecting wallet availability, handling connection requests, and updating the UI to reflect the connection status. I will also implement error handling and user feedback mechanisms to guide users through any issues.

After thorough testing to ensure everything works seamlessly, I will integrate the solution into the existing codebase and provide documentation for future maintenance and user onboarding.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hello I'm a frontend and a blockchain developer and I will love to work on this issue

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I have a strong background in front-end development, with extensive experience in building responsive web applications using modern frameworks such as React and Vue.js. My expertise includes creating intuitive user interfaces and integrating web3 functionality for blockchain applications. I have successfully implemented navigation systems and wallet connection features in previous projects, ensuring seamless user experiences. This background enables me to effectively design and implement a navigation bar and wallet connection component that enhances user interaction with the application.

### How I plan on tackling this issue
I would begin by outlining the requirements for the navigation bar and wallet connection component. This would include defining the links needed for the navigation (e.g., Home, About, Dashboard) and determining the desired wallet connection functionality (e.g., connecting, disconnecting, displaying wallet address).

Next, I would implement the navigation bar component using a responsive design, ensuring it is mobile-friendly. I would utilize a UI framework such as Material-UI or Tailwind CSS for consistent styling and to streamline development. The navigation links would be implemented with React Router for seamless client-side routing.

For the wallet connection component, I would integrate web3 libraries such as ethers.js or web3.js to manage wallet interactions. I would create a function to connect the user's wallet, ensuring that it handles various wallet providers (e.g., MetaMask, WalletConnect). The component would display the wallet address once connected and provide a button to disconnect if needed.

I would also ensure that the navigation bar and wallet connection component are accessible and follow best practices for user experience. This includes managing loading states during wallet connection, providing error handling for failed connections, and implementing responsive design principles.

Finally, I would conduct thorough testing to ensure all components function correctly across different devices and browsers. This structured approach will ensure that the navigation bar and wallet connection component are effectively implemented and provide a smooth user experience in the application.

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
i have prir experience in frontend

### How I plan on tackling this issue
follow along the aesthetics of the page and work on it

**Comment by caxtonacollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am applying to this issue via https://app.onlydust.com/hackathons/odhack-90.

I am Collins Cxaton, a fullstark developer with a strong background in integrating APIs and designing responsive UI components based on Figma designs. I have experience in working with cryptocurrency wallets and displaying real-time wallet balances by integrating financial APIs. My skills in React and JavaScript allow me to effectively manage currency conversions and data handling.

### How I plan on tackling this issue
i will love to contribute to this project

**Comment by josephpdf** [comment]
Hi!, my name is Joseph Poveda.
I am a student of the Systems Programming degree, I am a recent member of the Dojo Coding community, where I am getting started in the world of Web3.
I have basic knowledge of different programming languages ​​and thanks to this I hope to be able to resolve the issue.
I have knowledge of HTML and CSS. 
The first thing I would do is analyze the code a little to see how to implement the requested tag, I would do functional tests and add the connector for the wallets.

**Comment by Goodness5** [comment]
@josephchimebuka you can access figma design here in-case you ommited it in the contribution guidelines https://www.figma.com/design/3nZ7dFPCVz4fdnfP5ZGlL6/Custos-Diretriz?node-id=0-1&node-type=canvas&t=SZrQbCkWDo6zOuvO-0

**Comment by josephchimebuka** [comment]
Thank you @Goodness5, I'll get with now!

**Comment by Goodness5** [comment]
@josephchimebuka still waiting for your update on this

**Comment by josephchimebuka** [comment]
@Goodness5 I am also done just fixing a little error I am sending a draft PR RN
