### ISSUE TITLE
Agreement Feature

### ISSUE THREAD

**Issue by Khauthymo** [Custos-Diretriz/custos-mobile#4]
- [ ] Implement UI
- [ ] Connect to backend endpoint
- [ ] Connect to starknet contract

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/

### How I plan on tackling this issue
I will ensure that all the criteria on the description are met by implementing the UI and connnecting it to the backend endpoint and contract in 2-3 days

**Comment by abdegenius** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a fullstack developer with expertise across all the web2 space currently transitioning into the web3 space.

### How I plan on tackling this issue
I will create a well documented and written codebase that will capture every bit of detail of the figma design and bring it to live, with the animations, mobile responsiveness, dark and light mode features as well as componentization for reusability across other pages, also write the connection code and implement any backend / frontend interaction. i can very much handle this task!

**Comment by Ayoazeez26** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a software developer with 6 years experience building applications

### How I plan on tackling this issue
Implement ui according to figma design to pixel perfect integration
Connect the backend endpoint and test to ensure it works as expected
Connect to starknet contract and test to ensure it works as expected

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a frontend developer with experience in using react,  typescript , javascript, writing and connecting smart contract to dapp using cairo programming language and solidity.

**Comment by KevinLatino** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I have a deep passion for Web3 and I am currently working as a frontend developer intern at a Web2 company, focusing on Next.js. Additionally, I am an active member of Dojo Coding, a prominent Web3 community in LATAM, which has given me great exposure to decentralized technologies.

Recently, I have been working on a project for Base LATAM's Buildathon, where I am gaining hands-on experience in building decentralized applications. I am eager to continue growing and contributing, and see this as a fantastic opportunity to further develop my skills and make a significant impact.

This is my first OD Hack, so I will appreciate it if you give me the chance to contribute to this amazing project.

Some frontend projects that i have:                                                               
https://buildmyevent.xyz/
https://peritazgo-website.vercel.app/



### How I plan on tackling this issue
To address the issue, I would take the following steps:

Implement the UI: I would design and develop a user-friendly interface using a framework like React or Next to ensure responsiveness and accessibility.

Connect to the Backend Endpoint: I would establish a connection to the backend API using Axios or Fetch to handle data retrieval and submissions efficiently.

Integrate with the StarkNet Contract: I would utilize the StarkNet.js library to interact with the smart contract, ensuring proper handling of transaction requests and contract calls.

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in both frontend and backend.


### How I plan on tackling this issue
To solve this issue, I’ll take the following steps:
1.⁠ ⁠I’ll create NavBar component, using React Router for navigation, I’ll structure the component with links to various application routes. I’ll also implement a simple CSS file for styling
2.⁠ ⁠⁠I’ll create a NavBar.css file to style the navigation elements using Flexbox.
3.⁠ ⁠⁠I’ll implement wallet connection logic using ethers.js, and maintain the connected wallet address in local state.
4.⁠ ⁠⁠I’ll include the ConnectWallet component within the NavBar.
5.⁠ ⁠⁠ ⁠Then I’ll use BrowserRouter to wrap the application and implement route handling for different pages.
6.⁠ ⁠⁠Lastly, I’ll test to ensure that routing and wallet connection functionalities work as expected and also to verify responsiveness of the navigation bar for various screen sizes

Please assign me, I’m ready to work.

**Comment by Goodness5** [comment]
@od-hunter you can access figma design here incase you ommited it in the contribution guidelines https://www.figma.com/design/3nZ7dFPCVz4fdnfP5ZGlL6/Custos-Diretriz?node-id=0-1&node-type=canvas&t=SZrQbCkWDo6zOuvO-0

**Comment by faytey** [comment]
Due to the complexity of this issue and short time, i'd be assigning one more contributor to this issue to pair with @od-hunter and tidy up the integrations and UI before 3rd, who's up for this.
